# Generated by Django 4.2.5 on 2023-10-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='column',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='column',
            name='column_id',
        ),
    ]
