# Generated by Django 3.2 on 2023-10-06 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20231005_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='title',
        ),
    ]
